### ISSUE TITLE
HTML lang klopt niet

### ISSUE THREAD

**Issue by Jesse-Kramer** [christoph3r3w/user-experience-enhanced-website#1]
https://github.com/christoph3r3w/user-experience-enhanced-website/blob/d90cb39fcff06275482e61c302f560a5f4d951a3/views/partials/head.ejs#L2

De taal setting staat op Engels maar de website en posts staan in het nederlands.
Misschien een idee om dit op NL te zetten?

**Comment by christoph3r3w** [comment]
has been fixed 5d9dfb48525ea1c2c59af8e772ac3043eeb5cd34
