### ISSUE TITLE
Double """" inside width

### ISSUE THREAD

**Issue by Jesse-Kramer** [christoph3r3w/user-experience-enhanced-website#3]
![image](https://github.com/christoph3r3w/user-experience-enhanced-website/assets/91184609/c826b9c2-577c-4aef-b5f3-a1e232be4f50)

Omdat je de width uit de API haalt (denk ik) gaat dit nog niet helemaal goed. Je krijgt nu errors in de validator doordat je dubbele  "" hebt staan.

**Comment by christoph3r3w** [comment]
thanks and it has been fixed

https://github.com/christoph3r3w/user-experience-enhanced-website/blob/f708130c6e32c19878e779b20d45824c60e6987d/views/index.ejs#L25
