### ISSUE TITLE
Performance test 

### ISSUE THREAD

**Issue by Hadil66** [christoph3r3w/user-experience-enhanced-website#5]
Je hebt zowel bij de desktop als bij de mobile version een hoge score bij de cumulative layout shift, namelijk 0.014 op mobile en 0.013 op desktop. Ook maak je goed gebruik van lazy loading. 

<img src="https://github.com/christoph3r3w/user-experience-enhanced-website/assets/144008714/ad3a95a6-ee13-4536-81cc-59d7343a95e7" width="500px">

[Lazy loading & layout shift](https://github.com/christoph3r3w/user-experience-enhanced-website/blob/210d573823cceca0ef2e9c6a28082130b7e82d90/views/index.ejs#L21-L27)

[PageSpeed Insights](https://pagespeed.web.dev/analysis/https-user-experience-enhanced-website-c3ht-onrender-com/bzmcgw3156?form_factor=mobile)

Het is ook misschien handig om het `picture` element te gebruiken om een `img` heen. Het wordt gebruikt om verschillende versies van een afbeelding weer te geven, zoals avif en webp. 

[Picture MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)

**Comment by christoph3r3w** [comment]
Bedankt, ik zal deze tips in mijn volgende iteratie toepassen.
